name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository kodlarini al
        uses: actions/checkout@v4

      - name: Java 21 kur
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Java dosyalarini derle
        run: mkdir -p out && javac -encoding UTF-8 -d out src/*.java

      - name: Programi calistir
        run: java -cp out Main
